// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dlogs

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs(in *jlexer.Lexer, out *Tuple) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs(out *jwriter.Writer, in Tuple) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Tuple) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Tuple) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Tuple) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Tuple) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs(l, v)
}
func easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs1(in *jlexer.Lexer, out *DLog) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs1(out *jwriter.Writer, in DLog) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DLog) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DLog) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DLog) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DLog) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs1(l, v)
}
func easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs2(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ServerAddr":
			out.ServerAddr = string(in.String())
		case "ModeDebug":
			out.ModeDebug = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs2(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ServerAddr\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ServerAddr))
	}
	{
		const prefix string = ",\"ModeDebug\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ModeDebug))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAdfe8af4EncodeGithubComDoraLogsInternalDlogs2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAdfe8af4DecodeGithubComDoraLogsInternalDlogs2(l, v)
}
